services:
  backend:
    build: ./Controller+fastapi
    devices:
    - /dev:/dev
    environment:
    - TZ=America/New_York
    image: amscope-camera-backend:camera-1
    ports:
    - 8002:8000
    privileged: true
    restart: unless-stopped
  cam1:
    build: ./Controller+fastapi
    container_name: cam1
    devices:
    - /dev:/dev
    environment:
      PORT: '8000'
      TZ: America/New_York
    image: amscope-camera-backend:cam1
    ports:
    - 8000:8000
    privileged: true
    restart: unless-stopped
