services:
  backend:
    build: ./Controller+fastapi
    devices:
    - /dev:/dev
    environment:
    - TZ=America/New_York
    image: amscope-camera-backend:camera-1
    ports:
    - 8007:8000
    privileged: true
    restart: unless-stopped
