services:
  backend:
    build: ./Controller+fastapi
    devices:
    - /dev:/dev
    environment:
    - TZ=America/New_York
    image: amscope-camera:camera1
    ports:
    - 80:8001
    privileged: true
    restart: unless-stopped
